Rating system backend changes
skier233/stash pull request #3
Opened 2022-10-07 14:34 UTC by skier233

2022-10-18 22:38 UTC, WithoutPants requested changes

2022-10-18 22:38 UTC, WithoutPants commented on pkg/models/model_studio.go
> +	Rating        OptionalInt      `db:"rating" json:"rating"`
As per above notes, this should be left as `*sql.NullInt64` to be consistent with the rest of the fields.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_mutation_studio.go
> +	updatedStudio.Rating100 = translator.optionalInt(input.Rating100, "rating100")
`Rating` should be left a `sql.NullInt64`. Use `translator.nullInt64` to set rating from `input.Rating100`, translate `input.Rating` using `models.Rating5To100` if present.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_model_movie.go
> +	}
Use `models.Rating100To5` for this - don't reimplement the logic.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_model_performer.go
> +		return &rating, nil
Use `models.Rating100To5`.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_model_studio.go
> +		return &rating, nil
Use `models.Rating100To5`.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_mutation_movie.go
> +	updatedMovie.Rating100 = translator.optionalInt(input.Rating100, "rating100")
`Rating` should be left a `sql.NullInt64`. Use `translator.nullInt64` to set rating from `input.Rating100`, translate `input.Rating` using `models.Rating5To100` if present.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_mutation_movie.go
> +	updatedMovie.Rating100 = translator.optionalInt(input.Rating100, "rating100")
`Rating` should be left a `sql.NullInt64`. Use `translator.nullInt64` to set rating from `input.Rating100`, translate `input.Rating` using `models.Rating5To100` if present.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_mutation_performer.go
> +	updatedPerformer.Rating100 = translator.optionalInt(input.Rating100, "rating100")
`Rating` should be left a `sql.NullInt64`. Use `translator.nullInt64` to set rating from `input.Rating100`, translate `input.Rating` using `models.Rating5To100` if present.

2022-10-18 22:38 UTC, WithoutPants commented on internal/api/resolver_mutation_performer.go
> +	updatedPerformer.Rating100 = translator.optionalInt(input.Rating100, "rating100")
`Rating` should be left a `sql.NullInt64`. Use `translator.nullInt64` to set rating from `input.Rating100`, translate `input.Rating` using `models.Rating5To100` if present.

2022-10-18 22:38 UTC, WithoutPants commented on pkg/models/model_movie.go
> +	Rating    OptionalInt      `db:"rating" json:"rating"`
As per above notes, this should be left as `*sql.NullInt64` to be consistent with the rest of the fields.

2022-10-18 22:38 UTC, WithoutPants commented on pkg/models/model_performer.go
> +	Rating        OptionalInt      `db:"rating" json:"rating"`
As per above notes, this should be left as `*sql.NullInt64` to be consistent with the rest of the fields.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/gallery-slim.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/gallery.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/image-slim.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/image.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/movie-slim.graphql
> +  rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/movie.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/performer-slim.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/performer.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/scene-slim.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/scene.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/studio-slim.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-18 22:38 UTC, WithoutPants commented on graphql/documents/data/studio.graphql
>    rating
Remove `rating` if it's no longer in use in the UI.

2022-10-20 13:16 UTC, skier233 commented on graphql/documents/data/gallery-slim.graphql
>    rating
done

2022-10-20 13:17 UTC, skier233 commented on graphql/documents/data/studio.graphql
>    rating
done

2022-10-20 13:17 UTC, skier233 commented on graphql/documents/data/studio-slim.graphql
>    rating
done

2022-10-20 13:18 UTC, skier233 commented on graphql/documents/data/scene.graphql
>    rating
done

2022-10-20 13:19 UTC, skier233 commented on graphql/documents/data/performer-slim.graphql
>    rating
done

2022-10-20 13:19 UTC, skier233 commented on graphql/documents/data/image.graphql
>    rating
done

2022-10-20 13:20 UTC, skier233 commented on graphql/documents/data/image-slim.graphql
>    rating
done

2022-10-20 13:20 UTC, skier233 commented on graphql/documents/data/gallery.graphql
>    rating
done

2022-10-20 13:20 UTC, skier233 commented on graphql/documents/data/gallery-slim.graphql
>    rating
done

2022-10-20 13:25 UTC, skier233 commented on internal/api/resolver_mutation_movie.go
> +	updatedMovie.Rating100 = translator.optionalInt(input.Rating100, "rating100")
Switched to nullint64. I'm not entirely sure what you mean about translating input.Rating using models.Rating5to100. Do you mean doing that here? I thought that occurs in the resolver models?

2022-10-20 13:26 UTC, skier233 commented on internal/api/resolver_mutation_performer.go
> +	updatedPerformer.Rating100 = translator.optionalInt(input.Rating100, "rating100")
same as above

2022-10-20 13:28 UTC, skier233 commented on pkg/models/model_movie.go
> +	Rating    OptionalInt      `db:"rating" json:"rating"`
done

2022-10-20 13:28 UTC, skier233 commented on pkg/models/model_performer.go
> +	Rating        OptionalInt      `db:"rating" json:"rating"`
done

2022-10-20 13:30 UTC, skier233 commented on internal/api/resolver_model_studio.go
> +		return &rating, nil
switched

2022-10-20 13:30 UTC, skier233 commented on internal/api/resolver_model_performer.go
> +		return &rating, nil
switched

2022-10-20 13:31 UTC, skier233 commented on internal/api/resolver_model_movie.go
> +	}
originally wasn't sure that it was possible to access the rating100to5 from here because I'm not very familiar with scopes in go. Definitely agree its better to use the logic since its possible. done.

2022-10-20 13:32 UTC, skier233 commented on internal/api/resolver_mutation_studio.go
> +	updatedStudio.Rating100 = translator.optionalInt(input.Rating100, "rating100")
same as below

2022-10-20 13:33 UTC, skier233 commented on pkg/models/model_studio.go
> +	Rating        OptionalInt      `db:"rating" json:"rating"`
done

2022-10-20 13:48 UTC, skier233 commented on internal/api/resolver_mutation_movie.go
> +	updatedMovie.Rating100 = translator.optionalInt(input.Rating100, "rating100")
I think I understand now but have a look to make sure it's what you were thinking.

2022-10-25 02:57 UTC, WithoutPants requested changes
This is looking good enough to merge into your other branch, but the resolver issues will need to be resolved. I haven't reviewed the front end changes.

2022-10-25 02:57 UTC, WithoutPants commented on internal/api/resolver_mutation_movie.go
> +	}
This should be slightly different. The `translator` is used to differentiate between a passed `nil` value and a not-provided `nil` value. 

This is a rough draft and is untested:
```
legacyRating := translator.nullInt64(input.Rating, "rating")
if legacyRating != nil {
    if legacyRating.Valid {
        legacyRating.Int64 = int64(models.Rating5To100(int(legacyRating.Int64)))
    }
    updatedMovie.Rating = legacyRating
}
```

Since this is likely used in a couple of places, it might be worth moving into a common function or `changesetTranslator` method. This should probably occur before the handling of `rating100` since that should override the legacy one.

2022-10-25 02:57 UTC, WithoutPants commented on internal/api/resolver_mutation_movie.go
> +	}
As above.

2022-10-25 02:57 UTC, WithoutPants commented on internal/api/resolver_mutation_performer.go
> +	}
As per movie comments.

2022-10-25 02:57 UTC, WithoutPants commented on internal/api/resolver_mutation_performer.go
> +	}
As per movie comments.

2022-10-25 02:57 UTC, WithoutPants commented on internal/api/resolver_mutation_studio.go
> +	}
As per movie comments.

2022-10-25 12:54 UTC, skier233 commented on internal/api/resolver_mutation_movie.go
> +	}
I looked at moving it into a helper method. But, since each different type has a different input type, it would probably get more complex than its worth for this small of a block of shared code. Refactored it in these places.

2022-10-25 12:54 UTC, merged